# Generated by Django 5.1 on 2024-08-19 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('company_profile_pic', models.ImageField(blank=True, default='jobs/company/default.jpg', null=True, upload_to='jobs/company')),
                ('company_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobEducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('vacancy', models.IntegerField()),
                ('offer_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('experience', models.CharField(max_length=50)),
                ('post_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('job_status', models.CharField(choices=[('P', 'Published'), ('U', 'Unpublished')], db_index=True, default='P', max_length=1, verbose_name='Job Status')),
                ('preferred_age', models.CharField(blank=True, max_length=50, null=True)),
                ('cover_letter_required', models.CharField(choices=[('R', 'Required'), ('N', 'Not Required')], db_index=True, default='N', max_length=1, verbose_name='Cover Letter Requirement')),
                ('description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='jobs.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='jobs.country')),
                ('qualification_required', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobeducationlevel')),
                ('job_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobtype')),
            ],
        ),
    ]
