# Generated by Django 5.1 on 2024-08-26 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='Active', help_text='Status of the blog post', max_length=8),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
