# Generated by Django 5.1 on 2024-08-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_contactus2'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_map_url', models.URLField(help_text='URL for Google Maps embed', max_length=500)),
            ],
        ),
    ]
